### ISSUE TITLE
Clarification please : Vulnerable path in example from Section 3

### ISSUE THREAD

**Issue by IcarusBSilk** [lunasec-io/lunasec#292]
Hi, 

Need a clarification regarding the vulnerable log4j detected example under the [section 3](https://www.lunasec.io/docs/blog/log4j-zero-day-mitigation-guide/#3-determine-if-you-are-impacted-by-log4shell) "Determine if you are impacted by log4shell"

Please can you clarify if the MessagePatternConverter class is also to be removed in addition to JndiLookup.

Thanks in advance!

**Comment by breadchris** [comment]
Hey! Thanks for reaching out. We are working on improving the results from the scanner so that they are clearer for remediation. 

It should be noted that removing the class `MessagePatternConverter` will not patch the vulnerability and will actually cause the library to crash if used.

We will work on making this more clear by removing those results and only report `JndiLookup` matches.

You can follow the status of these changes here: https://github.com/lunasec-io/lunasec/pull/330.
