### ISSUE TITLE
“Log4Shell Update: Second log4j Vulnerability Published” blog post uses incorrect property name which is confusing

### ISSUE THREAD

**Issue by sainaen** [lunasec-io/lunasec#317]
The property/flag name should be `formatMsgNoLookups​` but in several places throughout [the post](https://www.lunasec.io/docs/blog/log4j-zero-day-update-on-cve-2021-45046/) it’s slightly different:

> You may still be vulnerable to Log4Shell (RCE) if you only enabled the `noMsgFormatLookups` flag

> Note that previous mitigations involving configuration such as to set the system property `log4j2.noFormatMsgLookup` to `true` do NOT mitigate this specific vulnerability.

> Issues when using `log4j2.noFormatMsgLookup` (>=2.10.0)

> The server is still vulnerable even with `log4j2.noFormatMsgLookup` enabled because

**Comment by breadchris** [comment]
Wow great catch! We just double checked our other posts thinking that we must have made a huge mistake and had in our mitigation strategy the wrong property to use, but instead we found something worse.

In our mitigation post we totally used the correct property name `formatMsgNoLookups` so we tried to figured out where on earth we got `noFormatMsgLookup` from. It turns out in the notice for `CVE-2021-45046` on the [log4j security page](https://logging.apache.org/log4j/2.x/security.html) they have the wrong mitigation property `log4j2.noFormatMsgLookup`. We must have copied this from the notice as we were writing about it!

We will update our blog to fix the property name typos and make note that the advisory has the incorrect property specified.

Thanks again for this report!
