### ISSUE TITLE
zerolog dependency

### ISSUE THREAD

**Issue by dminuoso** [lunasec-io/lunasec#325]
Hi.

The log4shell scanner tool is easily auditable, except for this odd dependency on zerolog:

https://github.com/lunasec-io/lunasec/blob/master/tools/log4shell/scan/scan.go#L23

I'm torn between laughter and sadness. Popularity of that logging library is definitely not an indicator of safety. After all, that's why this tool exists in the first place.

Is this really needed? Couldn't the standard library `log` be used instead?

**Comment by breadchris** [comment]
Hey! Thank you for reaching out. 

I understand that Log4Shell is a vulnerability in a structured logger and zerolog is being used as a structured logger in the scanner, however structured logging is important when communicating with someone who is using the CLI. 

zerolog was chosen specifically because of its simple design and accessible features. The only dependencies that it includes into the CLI is:

```
github.com/coreos/go-systemd/v22 v22.3.2
  github.com/godbus/dbus/v5 v5.0.4
github.com/pkg/errors v0.9.1
github.com/rs/xid v1.3.0
golang.org/x/tools v0.1.7
 github.com/yuin/goldmark
 and some more golang.org/x/* dependencies
```

`golang.org/x` dependencies are a part of the Golang project, but built outside of the main repo. And the rest are well known packages for solving common tasks in go.

For sure the `log` library in go could have been used, but much more code would have been needed in order get to the same level of versatility and cleanliness of the output from zerolog.

As a security engineer, I would deem this package safe to use in a project such as this one.
