### ISSUE TITLE
Query regarding vulnerable class file in log4j2

### ISSUE THREAD

**Issue by ankur-gupta-guavus** [lunasec-io/lunasec#374]
Hi,

I was using latest [release](https://github.com/lunasec-io/lunasec/releases/tag/v1.4.1-log4shell) of log4shell tool to scan hive metastore. It shows that there is one `log4j-core-2.8.2.jar`. 

I referred mitigations published on apache log4j website. There its mentioned:
```
Implement one of the following mitigation techniques:

- Java 8 (or later) users should upgrade to release 2.16.0.
- Java 7 users should upgrade to release 2.12.2.
- Otherwise, in any release other than 2.16.0, you may remove the JndiLookup class from the classpath: 
zip -q -d log4j-core-*.jar org/apache/logging/log4j/core/lookup/JndiLookup.class

```

I removed `JndiLookup.class` but tool still gives / rather shows vulnerable file. Only after removing `JndiManager.class` does the vulnerability goes away. Can someone please clarify do we have to remove both classes or just `JndiManager.class` ? 

```
sh-4.4# ./log4shell_1.4.1-log4shell_Linux_x86_64 scan --ignore-warnings /opt/apache-hive-metastore-3.0.0-bin/lib/
2:12PM Scan Result: Identified vulnerable path
	cve: CVE-2021-44228
	fileName: org/apache/logging/log4j/core/net/JndiManager.class
	hash: 764b06686dbe06e3d5f6d15891250ab04073a0d1c357d114b7365c70fa8a7407
	path: /opt/apache-hive-metastore-3.0.0-bin/lib/log4j-core-2.8.2.jar
	severity: 10.0
	versionInfo: 2.8.2
sh-4.4#

sh-4.4# jar tvf /opt/apache-hive-metastore-3.0.0-bin/lib/log4j-core-2.8.2.jar | grep -i jndi
  2974 Sun Apr 02 15:24:22 UTC 2017 org/apache/logging/log4j/core/lookup/JndiLookup.class
  4197 Sun Apr 02 15:24:24 UTC 2017 org/apache/logging/log4j/core/net/JndiManager.class
  1890 Sun Apr 02 15:24:24 UTC 2017 org/apache/logging/log4j/core/net/JndiManager$JndiManagerFactory.class
  4948 Sun Apr 02 15:24:24 UTC 2017 org/apache/logging/log4j/core/selector/JndiContextSelector.class
   249 Sun Apr 02 15:24:24 UTC 2017 org/apache/logging/log4j/core/net/JndiManager$1.class
   800 Sun Apr 02 15:24:24 UTC 2017 org/apache/logging/log4j/core/util/JndiCloser.class

sh-4.4# zip -q -d /opt/apache-hive-metastore-3.0.0-bin/lib/log4j-core-2.8.2.jar \*/JndiLookup.class

sh-4.4# jar tvf /opt/apache-hive-metastore-3.0.0-bin/lib/log4j-core-2.8.2.jar | grep -i jndi
  4197 Sun Apr 02 15:24:24 UTC 2017 org/apache/logging/log4j/core/net/JndiManager.class
  1890 Sun Apr 02 15:24:24 UTC 2017 org/apache/logging/log4j/core/net/JndiManager$JndiManagerFactory.class
  4948 Sun Apr 02 15:24:24 UTC 2017 org/apache/logging/log4j/core/selector/JndiContextSelector.class
   249 Sun Apr 02 15:24:24 UTC 2017 org/apache/logging/log4j/core/net/JndiManager$1.class
   800 Sun Apr 02 15:24:24 UTC 2017 org/apache/logging/log4j/core/util/JndiCloser.class

sh-4.4# ./log4shell_1.4.1-log4shell_Linux_x86_64 scan --ignore-warnings /opt/apache-hive-metastore-3.0.0-bin/lib/
2:17PM Scan Result: Identified vulnerable path
	cve: CVE-2021-44228
	fileName: org/apache/logging/log4j/core/net/JndiManager.class
	hash: 764b06686dbe06e3d5f6d15891250ab04073a0d1c357d114b7365c70fa8a7407
	path: /opt/apache-hive-metastore-3.0.0-bin/lib/log4j-core-2.8.2.jar
	severity: 10.0
	versionInfo: 2.8.2
sh-4.4#

sh-4.4# zip -q -d /opt/apache-hive-metastore-3.0.0-bin/lib/log4j-core-2.8.2.jar \*/JndiManager.class
sh-4.4# ./log4shell_1.4.1-log4shell_Linux_x86_64 scan --ignore-warnings /opt/apache-hive-metastore-3.0.0-bin/lib/
sh-4.4#
```

**Comment by freeqaz** [comment]
Hey @ankur-gupta-guavus, give me a minute to dig into this. We made some changes to the way that we were detecting files because, unfortunately, there are some false positives that makes this a little tricky to remediate.

You may be correct that you only need to remove `JndiLookup.class` and not `JndiManager.class` also. If that's true, I'll go through and verify our configuration to figure out what's going on + update which file we're checking for (if possible).

JAR scanning is a little tricky, as we've been learning, so thanks for filing this issue to help us iron out the kinks. :)

**Comment by breadchris** [comment]
@ankur-gupta-guavus our scanner, at the moment, unfortunately will only identify vulnerable package versions, but _will not_ identify vulnerable packages which have been remediated. 

What this means, as you have found out, is that the scanner will scan for the presence of `JndiManager.class`, but will not identify that `JndiLookup.class` is not present, which is the correct step for remediating this issue when you are patching the library in place.

Thank you for raising this issue. What you are doing for patching is correct with removing `JndiLookup.class`, please _do no_ remove `JndiManager.class`, your application will crash when started. We will work on a fix for this so that we are actually reporting if the vulnerability has been remediated or not for a given library.

**Comment by ankur-gupta-guavus** [comment]
Thanks for the clarification @freeqaz @breadchris
